-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:25:479: error: Tactic `split_ifs` failed: no if-then-else conditions to split
-- 
-- case refine_2
-- n i : ℤ
-- A : ℤ → ℤ
-- h_pre : 0 ≤ n
-- h_tau_0 : i ≤ n
-- h_guard : i < n
-- ⊢ sum A i + A i = sum A (i + 1)

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom sum : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((sum A 0) = 0)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ (k : Int), ((k ≥ 0) → ((sum A (k + 1)) = ((sum A k) + (A k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc1_fallthrough
    (n s i : Int)
    (A : Int → Int)
    (s' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (i ≤ n))
    (h_tau_1 : (s = (sum A i)))
    (h_guard : (i < n))
    (h_trans_s : s' = (s + (A i)))
    (h_trans_i : i' = (i + 1)) :
    ((i' ≤ n)) ∧ ((s' = (sum A i'))) := by
  subst_eqs
  refine ⟨?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
