-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:20:296: warning: aesop: failed to prove the goal after exhaustive search.
-- <tmp>.lean:20:303: error: unsolved goals
-- n s i : ℤ
-- A : ℤ → ℤ
-- i' : ℤ
-- h_pre : 0 ≤ n
-- h_not_g : n ≤ i'
-- ⊢ sum A i' = sum A n

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom sum : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((sum A 0) = 0)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ (k : Int), ((k ≥ 0) → ((sum A (k + 1)) = ((sum A k) + (A k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc4_fallthrough
    (n s i : Int)
    (A : Int → Int)
    (s' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (s' = (sum A i')))
    (h_not_g : ¬ ((i' < n))) :
    (s' = (sum A n)) := by
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done))
end SynthLean.VerifyTmp
