"""Compute signature hashes for a benchmark's Lean obligations.

Usage:

    python -m synth.lean_backend.hash benchmarks/<file>.py

For each soundness-critical safety constraint, prints:

    sc<idx>  kind=<kind>  branch=<idx-or-->  hash=<H>  filename=<stem>.solved.lean

The hashes are computed by translating each constraint to a Lean
theorem under the CANONICAL solution (every candidate atom of every
hole picked).  This is the same hash the solver's cache lookup
would use during synthesis, so the filename printed here is exactly
what a curator should create when writing `.solved.lean` or
`.invalid.lean` companions.

When a benchmark's eventually-chosen τ is a STRICT SUBSET of its
candidate atoms (e.g., factorial drops `n ≥ 0`), the printed hash
for the canonical solution will NOT match the hash the running
synthesizer computes.  Pass `--tau "atom1, atom2, ..."` to
override the τ subset for the relevant loop.

Implementation note: the Problem's `template` is mutated in place
by `expand()` (loop_id / block_id assignment).  We make a deep
copy first so the source benchmark file is unaffected.
"""
from __future__ import annotations

import argparse
import copy
import importlib.util
import sys
from pathlib import Path
from typing import Any

from ..constraints import generate
from ..expand import expand
from ..ir import Loop, Problem, SB, Seq
from ..result import Solution
from .translate import (
    emit_axiom_declarations,
    theorem_for_chain_bundle,
    theorem_for_entry_bundle,
    theorem_for_ranking_decrease,
    theorem_for_ranking_lb,
    theorem_for_safety_inductive,
)
from .verify import _signature_hash


def _load_problem(path: Path) -> Problem:
    """Load a benchmark file's `PROBLEM` symbol."""
    spec = importlib.util.spec_from_file_location("_bench", path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, "PROBLEM"):
        raise ValueError(f"{path}: no top-level PROBLEM symbol")
    return mod.PROBLEM


def _build_canonical_solution(
    problem: Problem,
    tau_override: dict[str, list[str]] | None = None,
) -> Solution:
    """Build the canonical Solution from `problem.atoms` (one atom
    per single-hot hole, all candidates for τ holes).  `tau_override`
    can replace specific τ holes' atom lists.
    """
    atoms: dict[str, Any] = {}
    for hole_id, candidates in problem.atoms.items():
        if not candidates:
            continue
        if hole_id.startswith("tau@"):
            if tau_override and hole_id in tau_override:
                atoms[hole_id] = list(tau_override[hole_id])
            else:
                atoms[hole_id] = list(candidates)
        else:
            atoms[hole_id] = candidates[0]
    return Solution(choices={}, atoms=atoms)


def _sb_branches_for_loop(problem: Problem, loop_id: str) -> int:
    """Return the loop body's SB branch count (1 for SB(n=1))."""
    for t in _walk(problem.template):
        if isinstance(t, Loop) and t.loop_id == loop_id:
            if isinstance(t.body, SB):
                return t.body.n
            return 1
    return 1


def _walk(node):
    """Yield every IR node in the template tree."""
    yield node
    if isinstance(node, Loop):
        yield from _walk(node.body)
    elif isinstance(node, Seq):
        yield from _walk(node.left)
        yield from _walk(node.right)


def _src_for_theorem(problem: Problem, theorem: str) -> str:
    """Wrap a theorem text the same way verify.py does, so the
    signature hash matches what the solver computes at runtime."""
    axioms = emit_axiom_declarations(problem)
    return (
        "-- Generated by synth.lean_backend.verify — DO NOT keep this file.\n"
        "import SynthLean.Basic\n"
        "open SynthLean\n"
        "\n"
        f"{axioms}"
        "namespace SynthLean.VerifyTmp\n"
        "\n"
        f"{theorem}"
        "end SynthLean.VerifyTmp\n"
    )


def _hash_for(
    problem: Problem,
    sol: Solution,
    sc_kind: str,
    loop_id: str,
    sc_idx: int,
    branch_idx: int | None,
) -> tuple[str, str]:
    """Return (signature_hash, expected_filename_stem) for a single
    (kind, loop, branch, sc_idx).  The filename stem is the form the
    solver writes via `_dump_failed_obligation` and the cache reads
    via `_consult_companions`.
    """
    theorem_name = f"sc{sc_idx}_fallthrough"
    if sc_kind == "ranking-lb":
        th = theorem_for_ranking_lb(
            problem, sol, loop_id, theorem_name=theorem_name
        )
    elif sc_kind == "ranking-decrease":
        th = theorem_for_ranking_decrease(
            problem, sol, loop_id, theorem_name=theorem_name,
            branch_idx=branch_idx,
        )
    elif sc_kind == "safety":
        th = theorem_for_safety_inductive(
            problem, sol, loop_id, theorem_name=theorem_name,
            branch_idx=branch_idx,
        )
    elif sc_kind == "safety-bundle-entry":
        th = theorem_for_entry_bundle(
            problem, sol, loop_id, theorem_name=theorem_name
        )
    elif sc_kind == "safety-bundle-post":
        th = theorem_for_chain_bundle(
            problem, sol, loop_id, theorem_name=theorem_name
        )
    else:
        return ("(untranslatable)", "")
    h = _signature_hash(_src_for_theorem(problem, th))
    return (h, f"{theorem_name}_{h}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("benchmark", type=Path,
                    help="Path to a benchmark file with a top-level PROBLEM")
    ap.add_argument("--tau", action="append", default=[],
                    metavar="HOLE=ATOM1;ATOM2;...",
                    help="Override a τ hole's atom list, "
                         "semicolon-separated to avoid commas inside "
                         "function calls (e.g., "
                         "--tau 'tau@L0=c == count(A, i); 0 <= i; i <= n').  "
                         "May be passed multiple times.")
    args = ap.parse_args(argv)

    tau_override: dict[str, list[str]] = {}
    for spec in args.tau:
        if "=" not in spec:
            ap.error(f"--tau spec missing `=`: {spec!r}")
        hole, atoms_str = spec.split("=", 1)
        atoms = [a.strip() for a in atoms_str.split(";") if a.strip()]
        tau_override[hole.strip()] = atoms

    problem = _load_problem(args.benchmark)
    # Deep-copy so expand()'s in-place mutation doesn't affect callers
    # that re-import the benchmark.
    p = copy.deepcopy(problem)
    scaffold = expand(p)
    system = generate(p, scaffold)
    sol = _build_canonical_solution(p, tau_override or None)

    print(f"# Benchmark: {args.benchmark}")
    if tau_override:
        print(f"# τ overrides: {tau_override}")
    print()
    header = f"{'sc_idx':<6} {'kind':<24} {'branch':<7} {'hash':<10}  filename"
    print(header)
    print("-" * len(header))
    for sc_idx, sc in enumerate(system.safety):
        loop_id = sc.loop_id
        if loop_id is None:
            print(f"{sc_idx:<6} {sc.kind:<24} {'-':<7} {'-':<10}  "
                  f"(loop_id=None; not Lean-translatable)")
            continue
        branch_idx = sc.branch_idx
        branch_label = "-" if branch_idx is None else str(branch_idx)
        try:
            h, stem = _hash_for(p, sol, sc.kind, loop_id, sc_idx, branch_idx)
        except Exception as e:
            print(f"{sc_idx:<6} {sc.kind:<24} {branch_label:<7} {'(error)':<10}  "
                  f"{type(e).__name__}: {e}")
            continue
        print(f"{sc_idx:<6} {sc.kind:<24} {branch_label:<7} {h:<10}  "
              f"{stem}.solved.lean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
