-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:24:413: warning: This simp argument is unused:
--   user_axiom_1
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵0̵,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵1̵]̵u̲s̲e̲r̲_̲a̲x̲i̲o̲m̲_̲0̲]̲
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom fact : Int → Int
axiom user_axiom_0 : ((fact 0) = 1)
axiom user_axiom_1 : (∀ k : Int, ((k ≥ 0) → ((fact (k + 1)) = ((k + 1) * (fact k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc1_fallthrough
    (n result i : Int)
    (result' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (result = (fact (i - 1))))
    (h_tau_1 : (i ≤ (n + 1)))
    (h_tau_2 : (n ≥ 0))
    (h_guard : (i ≤ n))
    (h_trans_result : result' = (result * i))
    (h_trans_i : i' = (i + 1)) :
    ((result' = (fact (i' - 1)))) ∧ ((i' ≤ (n + 1))) ∧ ((n ≥ 0)) := by
  subst_eqs
  refine ⟨?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
