-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom fact : Int → Int
axiom user_axiom_0 : ((fact 0) = 1)
axiom user_axiom_1 : (∀ k : Int, ((k ≥ 0) → ((fact (k + 1)) = ((k + 1) * (fact k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc1_fallthrough
    (n result i : Int)
    (result' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (n ≥ 0))
    (h_guard : (i ≤ n))
    (h_trans_result : result' = (result * i))
    (h_trans_i : i' = (i + 1)) :
    (n ≥ 0) := by
  subst_eqs
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop))
end SynthLean.VerifyTmp
