-- Lean returned ERROR (exit 1):
-- <tmp>.lean:18:2: error: omega could not prove the goal:
-- a possible counterexample may satisfy the constraints
--   b ≥ 1
--   a ≥ 0
--   a - b ≤ -2
-- where
--  a := n
--  b := i

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom fact : Int → Int
axiom user_axiom_0 : ((fact 0) = 1)
axiom user_axiom_1 : (∀ k : Int, ((k ≥ 0) → ((fact (k + 1)) = ((k + 1) * (fact k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc3_fallthrough
    (n result i : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (result = (fact (i - 1))))
    (h_tau_1 : (i ≥ 1))
    (h_tau_2 : (n ≥ 0)) :
    ((n + 1) - i) ≥ 0 := by
  omega
end SynthLean.VerifyTmp
