/-
fibonacci_array's NON-chain entry-bundle obligation (sc0 variant
generated by theorem_for_entry_bundle, distinct from
theorem_for_entry_bundle_chain).  Same τ subset:
{2 ≤ i, i ≤ n, ∀k. 0 ≤ k < i → C k = fib k}.

State at loop entry: C' = store (store C 0 0) 1 1, i' = 2.

Same proof shape as the chain-aware sc0:
  - 2 ≤ 2.
  - 2 ≤ n (from h_pre).
  - ∀k. 0 ≤ k < 2 → C' k = fib k:  k ∈ {0, 1}, both via store + user_axiom_{0,1}.
-/
import SynthLean.Core
open SynthLean

axiom fib : Int → Int
axiom user_axiom_0 : ((fib 0) = 0)
axiom user_axiom_1 : ((fib 1) = 1)
axiom user_axiom_2 :
  (∀ k : Int, ((k ≥ 0) → ((fib (k + 2)) = ((fib (k + 1)) + (fib k)))))

namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc0_fallthrough
    (n i : Int)
    (C : Int → Int)
    (i' : Int)
    (C' : Int → Int)
    (h_pre : (n ≥ 2))
    (h_init_C : C' = (store (store C 0 0) 1 1))
    (h_init_i : i' = 2) :
    ((2 ≤ i')) ∧ ((i' ≤ n)) ∧ ((∀ (k : Int), (((0 ≤ k) ∧ (k < i')) → ((C' k) = (fib k))))) := by
  subst h_init_C h_init_i
  refine ⟨?_, ?_, ?_⟩
  · omega
  · omega
  · intro k hk
    obtain ⟨hk_lo, hk_hi⟩ := hk
    by_cases h_k1 : k = 1
    · subst h_k1
      show (store (store C 0 0) 1 1) 1 = fib 1
      simp [store, user_axiom_1]
    · have h_k0 : k = 0 := by omega
      subst h_k0
      show (store (store C 0 0) 1 1) 0 = fib 0
      simp [store, user_axiom_0]

end SynthLean.VerifyTmp
