/-
fibonacci_array's NON-chain bundle-post obligation (sc4 variant
generated by theorem_for_chain_bundle, distinct from
theorem_for_chain_bundle_chain).

Same τ subset: {2 ≤ i, i ≤ n, ∀k. 0 ≤ k < i → C k = fib k}.
At loop exit: ¬(i' < n) ∧ i' ≤ n ⇒ i' = n.

Goal:  ∀k. 0 ≤ k < n → C' k = fib k.
Apply h_tau_2 (∀k. 0 ≤ k < i' → C' k = fib k) at k, where
k < n = i', so the hypothesis fires.
-/
import SynthLean.Core
open SynthLean

axiom fib : Int → Int
axiom user_axiom_0 : ((fib 0) = 0)
axiom user_axiom_1 : ((fib 1) = 1)
axiom user_axiom_2 :
  (∀ k : Int, ((k ≥ 0) → ((fib (k + 2)) = ((fib (k + 1)) + (fib k)))))

namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc4_fallthrough
    (n i : Int)
    (C : Int → Int)
    (i' : Int)
    (C' : Int → Int)
    (h_pre : (n ≥ 2))
    (h_tau_0 : (2 ≤ i'))
    (h_tau_1 : (i' ≤ n))
    (h_tau_2 : (∀ (k : Int), (((0 ≤ k) ∧ (k < i')) → ((C' k) = (fib k)))))
    (h_not_g : ¬ ((i' < n))) :
    (∀ (k : Int), (((0 ≤ k) ∧ (k < n)) → ((C' k) = (fib k)))) := by
  intro k hk
  obtain ⟨hk_lo, hk_hi⟩ := hk
  apply h_tau_2 k
  exact ⟨hk_lo, by omega⟩

end SynthLean.VerifyTmp
