-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:22:243: warning: This simp argument is unused:
--   user_axiom_0
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵0̵,̵ ̵user_axiom_1]
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom sum_range : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ p : Int, ((sum_range A p p) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ p q : Int, ((p ≤ q) → ((sum_range A p (q + 1)) = ((sum_range A p q) + (A q)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc0_fallthrough
    (n best i cur : Int)
    (A : Int → Int)
    (best' i' cur' : Int)
    (h_pre : (n ≥ 1))
    (h_init_best : best' = (A 0))
    (h_init_cur : cur' = (A 0))
    (h_init_i : i' = 1) :
    ((i' ≤ n)) ∧ ((∃ p : Int, ((0 ≤ p) ∧ (p ≤ (i' - 1)) ∧ ((sum_range A p i') = cur')))) ∧ ((∀ p q : Int, (((0 ≤ p) ∧ (p ≤ q) ∧ (q < i')) → ((sum_range A p (q + 1)) ≤ best')))) ∧ ((best' ≥ cur')) := by
  subst_eqs
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done)))
end SynthLean.VerifyTmp
