-- Lean returned ERROR (exit 1):
-- <tmp>.lean:16:2: error: omega could not prove the goal:
-- a possible counterexample may satisfy the constraints
--   a ≥ 1
--   a - b ≤ -1
-- where
--  a := n
--  b := i

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom sum_range : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ p : Int, ((sum_range A p p) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ p q : Int, ((p ≤ q) → ((sum_range A p (q + 1)) = ((sum_range A p q) + (A q)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc6_fallthrough
    (n best i cur : Int)
    (A : Int → Int)
    (h_pre : (n ≥ 1)) :
    (n - i) ≥ 0 := by
  omega
end SynthLean.VerifyTmp
