-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- n c : ℤ
-- M : ℤ → ℤ
-- G : ℤ → ℤ → ℤ
-- k : ℤ
-- h_tau_1 : k ≤ n
-- h_tau_3 : k ≤ c
-- h_guard : k < n - 1
-- left : 0 ≤ n
-- left_1 : 0 ≤ k
-- left_2 : ∀ (k : ℤ), 0 ≤ k → k < n → M k = -1
-- left_3 : k < n
-- right_1 : ¬k + 1 = -1
-- left_4 : ∀ (p q : ℤ), 0 ≤ p → p < n → 0 ≤ q → q < n → G p q = G q p
-- right : ∀ (k : ℤ), 0 ≤ k → k < n - 1 → 1 ≤ G k (k + 1)
-- ⊢ k + 1 < n

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom user_axiom_0 : (0 = 0)
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc2_fallthrough
    (n c i : Int)
    (M : Int → Int)
    (G : Int → Int → Int)
    (c' i' : Int)
    (M' : Int → Int)
    (h_pre : ((n ≥ 0) ∧ (∀ k : Int, (((0 ≤ k) ∧ (k < n)) → ((M k) = (-1)))) ∧ (∀ p q : Int, (((0 ≤ p) ∧ (p < n) ∧ (0 ≤ q) ∧ (q < n)) → (((G p) q) = ((G q) p)))) ∧ (∀ k : Int, (((0 ≤ k) ∧ (k < (n - 1))) → (((G k) (k + 1)) ≥ 1)))))
    (h_tau_0 : (0 ≤ i))
    (h_tau_1 : (i ≤ n))
    (h_tau_2 : (∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M k) ≠ (-1))) → ((0 ≤ (M k)) ∧ ((M k) < n) ∧ (((G k) (M k)) ≥ 1)))))
    (h_tau_3 : (c ≥ i))
    (h_guard : (i < (n - 1)))
    (h_trans_M : M' = (store (store M i (i + 1)) (i + 1) i))
    (h_trans_i : i' = (i + 2))
    (h_trans_c : c' = (c + 2)) :
    ((0 ≤ i')) ∧ ((i' ≤ n)) ∧ ((∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n) ∧ (((G k) (M' k)) ≥ 1))))) ∧ ((c' ≥ i')) := by
  subst_eqs
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
