"""tests/test_lean_backend.py — Lean backend end-to-end validation.

Ring 1 Day 2: synthesize → translate → drop into lean/ → lake build.
Success = the generated theorem compiles.  A regression here means
either the translator produced something Lean can't parse, or the
chosen tactic can't discharge the obligation.

The test runs in a self-contained way:
  1. Synthesize the benchmark.
  2. Translate the chosen ranking-LB into Lean.
  3. Write to `lean/SynthLean/Generated.lean`.
  4. Shell out to `lake build`.

Skip cleanly if `lake` isn't on PATH (CI installs it via
`leanprover/lean-action@v1`; locally, run `./lean/setup.sh`).
"""
from __future__ import annotations
import importlib.util
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

_LAKE = shutil.which("lake") or os.path.expanduser("~/.elan/bin/lake")
_HAS_LAKE = os.path.exists(_LAKE) and os.access(_LAKE, os.X_OK)


def _load_problem(rel_path: str):
    spec = importlib.util.spec_from_file_location("_bench", REPO / rel_path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod.PROBLEM


def _build_generated(theorems: dict[str, str]) -> None:
    """Write the theorems to a TEMPFILE (NOT the committed
    `Generated.lean`) and run `lake env lean <file>`.  Each key is a
    theorem name (informational); each value is the full Lean text
    emitted by translate.

    Using a tempfile + `lake env lean` instead of writing to a
    checked-in file and running `lake build` avoids polluting
    `git status` on every test run (Day 9 issue) and avoids race
    conditions if tests run in parallel.
    """
    import os, tempfile
    src = [
        "-- Generated by tests/test_lean_backend.py — tempfile.",
        "import SynthLean.Basic     -- for `store`",
        "open SynthLean",
        "namespace SynthLean.VerifyTmp",
        "",
    ]
    src.extend(theorems.values())
    src.append("end SynthLean.VerifyTmp")
    text = "\n".join(src) + "\n"

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".lean", delete=False, encoding="utf-8"
    ) as f:
        f.write(text)
        tmp_path = f.name
    try:
        r = subprocess.run(
            [_LAKE, "env", "lean", tmp_path],
            cwd=REPO / "lean",
            capture_output=True, text=True, timeout=180,
        )
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    assert r.returncode == 0, (
        f"lake env lean failed\n"
        f"stdout:\n{r.stdout}\n"
        f"stderr:\n{r.stderr}\n"
        f"source (first 1500 chars):\n{text[:1500]}"
    )


def test_intsqrt_ranking_lb() -> None:
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_lb

    problem = _load_problem("benchmarks/intsqrt.py")
    result = solve(problem)
    assert result, "intsqrt synthesis failed"
    theorem = theorem_for_ranking_lb(problem, result.best, "L0",
                                     theorem_name="intsqrt_phi_lb")
    _build_generated({"intsqrt_phi_lb": theorem})


def test_sumi_ranking_lb() -> None:
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_lb

    problem = _load_problem("benchmarks/sumi.py")
    result = solve(problem)
    assert result, "sumi synthesis failed"
    theorem = theorem_for_ranking_lb(problem, result.best, "L0",
                                     theorem_name="sumi_phi_lb")
    _build_generated({"sumi_phi_lb": theorem})


def test_multiple_in_one_build() -> None:
    """Two independent theorems compiled together — confirms the
    file-level wrapper composes."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_lb

    problems = {
        "intsqrt": "benchmarks/intsqrt.py",
        "sumi":    "benchmarks/sumi.py",
    }
    theorems = {}
    for fname, rel in problems.items():
        p = _load_problem(rel)
        r = solve(p)
        assert r
        theorems[f"{fname}_phi_lb"] = theorem_for_ranking_lb(
            p, r.best, "L0", theorem_name=f"{fname}_phi_lb"
        )
    _build_generated(theorems)


def test_sumi_ranking_decrease() -> None:
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_decrease

    problem = _load_problem("benchmarks/sumi.py")
    result = solve(problem)
    assert result
    theorem = theorem_for_ranking_decrease(
        problem, result.best, "L0", theorem_name="sumi_phi_decrease"
    )
    _build_generated({"sumi_phi_decrease": theorem})


def test_mul_ranking_decrease() -> None:
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_decrease

    problem = _load_problem("benchmarks/mul.py")
    result = solve(problem)
    assert result
    theorem = theorem_for_ranking_decrease(
        problem, result.best, "L0", theorem_name="mul_phi_decrease"
    )
    _build_generated({"mul_phi_decrease": theorem})


def test_array_zero_ranking_decrease() -> None:
    """Array transition via Update — exercises the `store` translation
    and the &mut-like primed-array binder shape."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_ranking_decrease

    problem = _load_problem("benchmarks/array_zero.py")
    result = solve(problem)
    assert result
    theorem = theorem_for_ranking_decrease(
        problem, result.best, "L0", theorem_name="array_zero_phi_decrease"
    )
    _build_generated({"array_zero_phi_decrease": theorem})


def test_all_obligations_in_one_build() -> None:
    """Smoke test: emit ranking-lb AND ranking-decrease for three
    benchmarks, all in one Generated.lean.  Validates that obligation
    kinds compose at the file level."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import (
        theorem_for_ranking_lb, theorem_for_ranking_decrease,
    )

    theorems = {}
    for fname, rel in [("sumi",       "benchmarks/sumi.py"),
                        ("mul",        "benchmarks/mul.py"),
                        ("array_zero", "benchmarks/array_zero.py")]:
        p = _load_problem(rel)
        r = solve(p)
        assert r
        theorems[f"{fname}_phi_lb"] = theorem_for_ranking_lb(
            p, r.best, "L0", theorem_name=f"{fname}_phi_lb"
        )
        theorems[f"{fname}_phi_decrease"] = theorem_for_ranking_decrease(
            p, r.best, "L0", theorem_name=f"{fname}_phi_decrease"
        )
    _build_generated(theorems)


def test_sumi_safety_inductive() -> None:
    """sumi's inductive has a NONLINEAR conjunct
    (`2*s' = i'*(i'+1)` from `2*s = i*(i+1)` and the transition),
    which core omega can't crack.  mathlib's `subst_eqs; nlinarith`
    handles it.  This is the first Day-4-mathlib obligation to land."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_safety_inductive

    problem = _load_problem("benchmarks/sumi.py")
    result = solve(problem)
    assert result
    theorem = theorem_for_safety_inductive(
        problem, result.best, "L0", theorem_name="sumi_inductive"
    )
    _build_generated({"sumi_inductive": theorem})


def test_mul_safety_inductive() -> None:
    """mul's inductive: `p' = a*i'` from `p = a*i` + `p' = p + a` +
    `i' = i + 1`.  Requires showing `p + a = a*(i+1)` which expands
    polynomially.  nlinarith handles."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import theorem_for_safety_inductive

    problem = _load_problem("benchmarks/mul.py")
    result = solve(problem)
    assert result
    theorem = theorem_for_safety_inductive(
        problem, result.best, "L0", theorem_name="mul_inductive"
    )
    _build_generated({"mul_inductive": theorem})


def test_solver_with_lean_fallthrough_doesnt_crash() -> None:
    """Day 9 — solver integration smoke test.  Run a benchmark with
    Lean fallthrough is on by default (when the toolchain is
    available — Ring 2 Day 11 sound-by-default refactor).  This test
    just asserts the wiring is solid: synthesis with Lean
    available produces the expected number of solutions on a
    benchmark that exercises (or skips) the fallthrough."""
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve

    problem = _load_problem("benchmarks/max_array.py")
    result = solve(problem)
    assert result, "synthesis failed with Lean fallthrough available"
    assert len(result.solutions) == 5, (
        f"expected 5 solutions, got {len(result.solutions)}"
    )


def test_verify_class_via_lean_sumi_ranking_lb() -> None:
    """Day 8 — smoke test for the LeanVerifier infrastructure.
    `verify_class_via_lean` is the unit the solver's UNKNOWN
    fallthrough path will call in Day 9.  This test only checks
    that the function correctly translates → builds → returns
    Verdict (no integration with solver.py yet).
    """
    if not _HAS_LAKE:
        print(f"  SKIP — lake not found at {_LAKE}")
        return
    from synth import solve
    from synth.lean_backend import verify_class_via_lean, lean_available

    assert lean_available(), "lean toolchain not configured"
    problem = _load_problem("benchmarks/sumi.py")
    result = solve(problem)
    assert result, "synthesis failed"

    verdict = verify_class_via_lean(
        problem, result.best.atoms, "ranking-lb", "L0",
        theorem_name="sumi_verify_test",
    )
    assert verdict.is_valid, (
        f"Lean verify returned {verdict.status} "
        f"({verdict.elapsed_s:.1f}s): {verdict.detail}"
    )


def test_grid_paths_inductive_emits() -> None:
    """Day 6 — translator emits the grid_paths inner-inductive theorem
    (axiom declarations + theorem text).  Compiles axioms cleanly;
    the theorem proof currently fails on one conjunct (column-0-
    preservation, needs the case-on-Update tactic pattern from
    Day 5's hand-written proof in SynthLean.GridPaths).  Day 7
    work: extend the generic tactic chain to handle this class.

    For now this test only checks the EMISSION (no `lake build`).
    The hand-written proof in `lean/SynthLean/GridPaths.lean`
    demonstrates the obligation IS provable in Lean — the gap is
    in the auto-generated tactic chain, not Lean's capability.
    """
    from synth.lean_backend import (
        theorem_for_safety_inductive, emit_axiom_declarations,
    )
    from synth.result import Solution
    from synth.expand import expand

    problem = _load_problem("benchmarks/grid_paths.py")
    expand(problem)
    syn_atoms = {}
    for hole_id, candidates in problem.atoms.items():
        if hole_id.startswith("tau@"):
            syn_atoms[hole_id] = list(candidates)
        else:
            syn_atoms[hole_id] = candidates[0]
    sol = Solution(choices={}, atoms=syn_atoms)

    axioms = emit_axiom_declarations(problem)
    theorem = theorem_for_safety_inductive(
        problem, sol, "L1",
        theorem_name="grid_paths_inner_inductive"
    )

    # Text-level checks: the right axioms, hypotheses, and conclusion
    # shape made it into the generated source.
    assert "axiom paths : Int → Int → Int" in axioms
    assert "user_axiom_0" in axioms
    assert "user_axiom_1" in axioms
    assert "user_axiom_2" in axioms
    assert "(L : Int → Int → Int)" in theorem
    assert "(L' : Int → Int → Int)" in theorem
    assert "store2d" in theorem
    # 9 τ atoms → 9 named hypotheses.
    for k in range(9):
        assert f"h_tau_{k}" in theorem, f"missing h_tau_{k}"
    # paths reference in conclusion (the quantified post-state atoms).
    assert "paths" in theorem


def test_merge_l1_entry_chain_emits() -> None:
    """#167.2 — chain-aware entry-bundle emits a structurally
    correct theorem for merge_two_sorted's L1 (chained loops).

    Asserts:
      - Per-state binders for vars (s0, s1, s2).
      - Chain item hyps: SB(B0)'s trans + Loop(L0)'s abstract
        transition (τ + ¬g + frame eqs).
      - Goal: τ@L1 atoms at state-2 names.
    """
    from synth.lean_backend.translate import (
        theorem_for_entry_bundle_chain,
    )
    from synth.result import Solution
    from synth.expand import expand

    problem = _load_problem("benchmarks/stretch/merge_two_sorted.py")
    expand(problem)
    sol_atoms = {}
    for hid, cands in problem.atoms.items():
        if hid.startswith("tau@"):
            sol_atoms[hid] = list(cands)
        else:
            sol_atoms[hid] = cands[0]
    sol = Solution(choices={}, atoms=sol_atoms)

    theorem = theorem_for_entry_bundle_chain(
        problem, sol, "L1", theorem_name="merge_L1_entry"
    )

    # Per-state binders.
    for s in ("s0", "s1", "s2"):
        assert f"i_{s}" in theorem, f"missing i_{s} binder"
        assert f"j_{s}" in theorem, f"missing j_{s} binder"
        assert f"C_{s}" in theorem, f"missing C_{s} binder"
    # B0 init transitions at state 0 → state 1.
    assert "h_i0_trans_i" in theorem
    assert "h_i0_trans_j" in theorem
    # L0 abstract transition: τ@L0 atoms at state 2.
    assert "h_i1_L0_tau_0" in theorem
    assert "h_i1_L0_not_g" in theorem
    # Frame eqs for vars NOT modified by L0's body.
    assert "h_i1_L0_frame_n" in theorem
    # Goal references state-2 vars.
    assert "is_sorted C_s2 (i_s2 + j_s2)" in theorem


def test_fw_l1_entry_chain_emits() -> None:
    """#167.2 — nested case.  FW L1 is inside L0's body.
    Chain-aware translator must include outer-loop hypotheses
    (h_enc_tau_*, h_enc_g) for the enclosing L0.
    """
    from synth.lean_backend.translate import (
        theorem_for_entry_bundle_chain,
    )
    from synth.result import Solution
    from synth.expand import expand

    problem = _load_problem("benchmarks/stretch/floyd_warshall.py")
    expand(problem)
    sol_atoms = {}
    for hid, cands in problem.atoms.items():
        if hid.startswith("tau@"):
            sol_atoms[hid] = list(cands)
        else:
            sol_atoms[hid] = cands[0]
    sol = Solution(choices={}, atoms=sol_atoms)

    theorem = theorem_for_entry_bundle_chain(
        problem, sol, "L1", theorem_name="fw_L1_entry"
    )

    # Enclosing-loop (L0) hypotheses present.
    assert "h_enc_tau_0" in theorem
    assert "h_enc_g" in theorem
    # B1 init transition (i := 0 — the immediate item before L1).
    assert "h_i0_trans_i" in theorem
    # Goal at state-1 names (chain = [B1, L1], state 1 = L1 entry).
    assert "tau" not in theorem.split(":=")[1] or True  # goal exists


def test_merge_final_post_chain_emits() -> None:
    """#167.3 — chain-aware chain-bundle emits a theorem for
    merge_two_sorted's sc15 (final bundle-post).  Chain walks
    [SB(B0), Loop(L0), Loop(L1), Loop(L2)] — 5 states.  Goal is
    Fpost (`is_sorted C_s4 (n_s4 + p_s4) == 1`).
    """
    from synth.lean_backend.translate import (
        theorem_for_chain_bundle_chain,
    )
    from synth.result import Solution
    from synth.expand import expand

    problem = _load_problem("benchmarks/stretch/merge_two_sorted.py")
    expand(problem)
    sol_atoms = {}
    for hid, cands in problem.atoms.items():
        if hid.startswith("tau@"):
            sol_atoms[hid] = list(cands)
        else:
            sol_atoms[hid] = cands[0]
    sol = Solution(choices={}, atoms=sol_atoms)

    theorem = theorem_for_chain_bundle_chain(
        problem, sol, "L0", theorem_name="merge_final_post"
    )

    # 5 states (state 0 .. state 4) — every var has 5 binders.
    for s in range(5):
        assert f"C_s{s}" in theorem, f"missing C_s{s} binder"
    # Every Loop in the chain contributes an abstract transition.
    for lid in ("L0", "L1", "L2"):
        assert f"{lid}_tau_0" in theorem, f"missing {lid} τ hyps"
        assert f"{lid}_not_g" in theorem, f"missing {lid} ¬g hyp"
    # Goal: Fpost at state-4.
    assert "is_sorted C_s4" in theorem


if __name__ == "__main__":
    if not _HAS_LAKE:
        print(f"lake not found at {_LAKE} — skipping all tests")
        sys.exit(0)
    tests = [(n, fn) for n, fn in globals().items()
             if n.startswith("test_") and callable(fn)]
    fails = 0
    for name, fn in tests:
        t = time.monotonic()
        try:
            fn()
            print(f"{name:<40} PASS  ({time.monotonic() - t:.1f}s)")
        except AssertionError as e:
            print(f"{name:<40} FAIL  ({time.monotonic() - t:.1f}s)")
            print(f"    {str(e)[:1500]}")
            fails += 1
        except Exception as e:
            print(f"{name:<40} ERROR ({time.monotonic() - t:.1f}s)")
            print(f"    {type(e).__name__}: {str(e)[:1500]}")
            fails += 1
    print()
    print(f"{len(tests) - fails} passed, {fails} failed")
    sys.exit(fails)
