-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:28:521: error: Tactic `split_ifs` failed: no if-then-else conditions to split
-- 
-- case refine_1
-- G n M i : ℤ
-- h_pre : 0 ≤ n
-- h_tau_0 : is_valid_pm G n i M = 1
-- h_tau_1 : i ≤ n
-- h_guard : i < n
-- ⊢ is_valid_pm G n (i + 1) (process_endpoint M i) = 1

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom is_valid_pm : Int → Int → Int → Int → Int
axiom is_max_matching : Int → Int → Int → Int
axiom empty_matching : Int
axiom process_endpoint : Int → Int → Int
axiom user_axiom_0 : (∀ G_ n_ : Int, ((is_valid_pm G_ n_ 0 (empty_matching )) = 1))
axiom user_axiom_1 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (process_endpoint M_ k_)) = 1)))
axiom user_axiom_2 : (∀ G_ n_ M_ : Int, (((is_valid_pm G_ n_ n_ M_) = 1) → ((is_max_matching G_ n_ M_) = 1)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc2_fallthrough
    (G n M i : Int)
    (M' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : ((is_valid_pm G n i M) = 1))
    (h_tau_1 : (i ≤ n))
    (h_guard : (i < n))
    (h_trans_M : M' = (process_endpoint M i))
    (h_trans_i : i' = (i + 1)) :
    (((is_valid_pm G n i' M') = 1)) ∧ ((i' ≤ n)) := by
  subst_eqs
  refine ⟨?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
