-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:23:108: error: linarith failed to find a contradiction
-- case h
-- G n M i : ℤ
-- h_pre : n ≥ 0
-- h_tau_0 : 0 ≤ i
-- a✝ : n - i < 0
-- ⊢ False
-- failed

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
import SynthLean.CostLemmas
open SynthLean

axiom is_valid_pm : Int → Int → Int → Int → Int
axiom is_max_matching : Int → Int → Int → Int
axiom empty_matching : Int
axiom process_endpoint : Int → Int → Int
axiom user_axiom_0 : (∀ G_ n_ : Int, ((is_valid_pm G_ n_ 0 (empty_matching )) = 1))
axiom user_axiom_1 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (process_endpoint M_ k_)) = 1)))
axiom user_axiom_2 : (∀ G_ n_ M_ : Int, (((is_valid_pm G_ n_ n_ M_) = 1) → ((is_max_matching G_ n_ M_) = 1)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
open SynthLean.CostLemmas in
theorem sc6_fallthrough
    (G n M i : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (0 ≤ i)) :
    (n - i) ≥ 0 := by
  first | omega | (ring_nf; omega) | nlinarith | (simp only [mul_comm, mul_add, add_mul]; ring_nf; omega) | linarith
end SynthLean.VerifyTmp
