-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom user_axiom_0 : (0 = 0)
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc0_fallthrough
    (n u v z w : Int)
    (M : Int → Int)
    (G : Int → Int → Int)
    (w' : Int)
    (h_pre : ((n ≥ 0) ∧ (0 ≤ u) ∧ (u < n) ∧ (0 ≤ v) ∧ (v < n) ∧ (0 ≤ z) ∧ (z < n) ∧ (u ≠ v) ∧ (u ≠ z) ∧ (v ≠ z) ∧ (∀ (k : Int), (((0 ≤ k) ∧ (k < n) ∧ ((M k) ≠ (-1))) → ((0 ≤ (M k)) ∧ ((M k) < n)))) ∧ ((M u) = (-1)) ∧ ((M v) = z) ∧ ((M z) = v) ∧ (((G u) v) ≥ 1) ∧ (∀ (p : Int) (q : Int), (((0 ≤ p) ∧ (p < n) ∧ (0 ≤ q) ∧ (q < n)) → (((G p) q) = ((G q) p))))))
    (h_init_w : w' = 0) :
    ((0 ≤ w')) ∧ ((w' ≤ n)) ∧ ((∀ (k : Int), (((0 ≤ k) ∧ (k < n) ∧ ((M k) ≠ (-1))) → ((0 ≤ (M k)) ∧ ((M k) < n))))) := by
  subst_eqs
  refine ⟨?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; first | rfl | omega | nlinarith | (aesop; done)))
end SynthLean.VerifyTmp
