-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:26:146: error: Tactic `simp` failed with a nested error:
-- (deterministic) timeout at `simp`, maximum number of heartbeats (200000) has been reached
-- 
-- Note: Use `set_option maxHeartbeats <num>` to set the limit.
-- 
-- Hint: Additional diagnostic information may be available using the `set_option diagnostics true` command.

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom user_axiom_0 : (0 = 0)
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc2_fallthrough
    (m n i : Int)
    (edges M : Int → Int)
    (i' : Int)
    (M' : Int → Int)
    (h_pre : ((n ≥ 0) ∧ (m ≥ 0) ∧ (∀ k : Int, (((0 ≤ k) ∧ (k < n)) → ((M k) = (-1)))) ∧ (∀ j : Int, (((0 ≤ j) ∧ (j < m)) → ((0 ≤ (edges (2 * j))) ∧ ((edges (2 * j)) < n) ∧ (0 ≤ (edges ((2 * j) + 1))) ∧ ((edges ((2 * j) + 1)) < n) ∧ ((edges (2 * j)) ≠ (edges ((2 * j) + 1))))))))
    (h_tau_0 : (0 ≤ i))
    (h_tau_1 : (i ≤ m))
    (h_tau_2 : (∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M k) ≠ (-1))) → ((0 ≤ (M k)) ∧ ((M k) < n)))))
    (h_tau_3 : (∀ j : Int, (((0 ≤ j) ∧ (j < i)) → (¬ (((M (edges (2 * j))) = (-1)) ∧ ((M (edges ((2 * j) + 1))) = (-1)))))))
    (h_guard : ((i < m) ∧ (((M (edges (2 * i))) = (-1)) ∧ ((M (edges ((2 * i) + 1))) = (-1)))))
    (h_trans_M : M' = (store (store M (edges (2 * i)) (edges ((2 * i) + 1))) (edges ((2 * i) + 1)) (edges (2 * i))))
    (h_trans_i : i' = (i + 1)) :
    ((0 ≤ i')) ∧ ((i' ≤ m)) ∧ ((∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n))))) ∧ ((∀ j : Int, (((0 ≤ j) ∧ (j < i')) → (¬ (((M' (edges (2 * j))) = (-1)) ∧ ((M' (edges ((2 * j) + 1))) = (-1))))))) := by
  subst_eqs
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
