-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- j : ℤ
-- a : 0 ≤ j
-- a_1 : j < m
-- a_2 : M' (edges (2 * j)) = -1
-- left : 0 ≤ n
-- left_1 : 0 ≤ m
-- left_2 : ∀ (k : ℤ), 0 ≤ k → k < n → M k = -1
-- right :
--   ∀ (j : ℤ),
--     0 ≤ j →
--       j < m →
--         0 ≤ edges (2 * j) ∧
--           edges (2 * j) < n ∧ 0 ≤ edges (2 * j + 1) ∧ edges (2 * j + 1) < n ∧ ¬edges (2 * j) = edges (2 * j + 1)
-- a_3 : M' (edges (2 * j + 1)) = -1
-- ⊢ False

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom user_axiom_0 : (0 = 0)
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc7_fallthrough
    (m n i : Int)
    (edges M : Int → Int)
    (i' : Int)
    (M' : Int → Int)
    (h_pre : ((n ≥ 0) ∧ (m ≥ 0) ∧ (∀ k : Int, (((0 ≤ k) ∧ (k < n)) → ((M k) = (-1)))) ∧ (∀ j : Int, (((0 ≤ j) ∧ (j < m)) → ((0 ≤ (edges (2 * j))) ∧ ((edges (2 * j)) < n) ∧ (0 ≤ (edges ((2 * j) + 1))) ∧ ((edges ((2 * j) + 1)) < n) ∧ ((edges (2 * j)) ≠ (edges ((2 * j) + 1))))))))
    (h_tau_0 : (0 ≤ i'))
    (h_tau_1 : (i' ≤ m))
    (h_tau_2 : (∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n)))))
    (h_tau_3 : (∀ j : Int, (((0 ≤ j) ∧ (j < i')) → (¬ (((M' (edges (2 * j))) = (-1)) ∧ ((M' (edges ((2 * j) + 1))) = (-1)))))))
    (h_not_g : ¬ ((i' < m))) :
    ((∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n)))) ∧ (∀ j : Int, (((0 ≤ j) ∧ (j < m)) → (¬ (((M' (edges (2 * j))) = (-1)) ∧ ((M' (edges ((2 * j) + 1))) = (-1))))))) := by
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; first | rfl | omega | nlinarith | (aesop; done))
end SynthLean.VerifyTmp
