/-
modular_exponentiation sc0_fallthrough for τ subset
{empty}.

Auto-generated by /tmp/modular_exp_curator.py.
-/
import SynthLean.Core
open SynthLean

axiom pow : Int → Int → Int
axiom user_axiom_0 : (∀ x : Int, ((pow x 0) = 1))
axiom user_axiom_1 : (∀ x k : Int, ((k ≥ 0) → ((pow x (k + 1)) = (x * (pow x k)))))
axiom user_axiom_2 : (∀ x k : Int, ((k ≥ 0) → ((pow x (2 * k)) = (pow (x * x) k))))
axiom user_axiom_3 : (∀ x y mm : Int, ((mm ≥ 1) → (((x * y) % mm) = (((x % mm) * (y % mm)) % mm))))

-- Helper: pow respects modular reduction (derivable by induction
-- from axioms 0, 1, 3).
private axiom pow_mod_base (x k mm : Int) (hk : k ≥ 0) (hm : mm ≥ 1) :
    (pow (x % mm) k) % mm = (pow x k) % mm

namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc0_fallthrough
    (b e m result base exp : Int)
    (result' base' exp' : Int)
    (h_pre : ((e ≥ 0) ∧ (m ≥ 1)))
    (h_init_result : result' = (1 % m))
    (h_init_base : base' = b)
    (h_init_exp : exp' = e) :
    ((result' ≥ 0)) ∧ ((result' < m)) := by
  subst_eqs
  obtain ⟨h_e_nn, h_m⟩ := h_pre
  refine ⟨?_, ?_⟩
  · exact Int.emod_nonneg _ (by omega : m ≠ 0)
  · exact Int.emod_lt_of_pos _ (by omega : (0 : Int) < m)

end SynthLean.VerifyTmp
