-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom pow : Int → Int → Int
axiom user_axiom_0 : (∀ x : Int, ((pow x 0) = 1))
axiom user_axiom_1 : (∀ x k : Int, ((k ≥ 0) → ((pow x (k + 1)) = (x * (pow x k)))))
axiom user_axiom_2 : (∀ x k : Int, ((k ≥ 0) → ((pow x (2 * k)) = (pow (x * x) k))))
axiom user_axiom_3 : (∀ x y mm : Int, ((mm ≥ 1) → (((x * y) % mm) = (((x % mm) * (y % mm)) % mm))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc0_fallthrough
    (b e m result base exp : Int)
    (result' base' exp' : Int)
    (h_pre : ((e ≥ 0) ∧ (m ≥ 1)))
    (h_init_result : result' = (1 % m))
    (h_init_base : base' = b)
    (h_init_exp : exp' = e) :
    ((exp' ≥ 0)) ∧ ((result' ≥ 0)) := by
  subst_eqs
  refine ⟨?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; first | rfl | omega | nlinarith | (aesop; done)))
end SynthLean.VerifyTmp
