/-
modular_exponentiation sc2_fallthrough for τ subset
{exp_nn, pow_inv, res_lt_m}.

Auto-generated by /tmp/modular_exp_curator.py.
-/
import SynthLean.Basic
open SynthLean

axiom pow : Int → Int → Int
axiom user_axiom_0 : (∀ x : Int, ((pow x 0) = 1))
axiom user_axiom_1 : (∀ x k : Int, ((k ≥ 0) → ((pow x (k + 1)) = (x * (pow x k)))))
axiom user_axiom_2 : (∀ x k : Int, ((k ≥ 0) → ((pow x (2 * k)) = (pow (x * x) k))))
axiom user_axiom_3 : (∀ x y mm : Int, ((mm ≥ 1) → (((x * y) % mm) = (((x % mm) * (y % mm)) % mm))))

-- Helper: pow respects modular reduction (derivable by induction
-- from axioms 0, 1, 3).
private axiom pow_mod_base (x k mm : Int) (hk : k ≥ 0) (hm : mm ≥ 1) :
    (pow (x % mm) k) % mm = (pow x k) % mm

namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc2_fallthrough
    (b e m result base exp : Int)
    (result' base' exp' : Int)
    (h_pre : ((e ≥ 0) ∧ (m ≥ 1)))
    (h_tau_0 : (exp ≥ 0))
    (h_tau_1 : (((result * (pow base exp)) % m) = ((pow b e) % m)))
    (h_tau_2 : (result < m))
    (h_guard : ((exp > 0) ∧ ((exp % 2) = 1)))
    (h_trans_result : result' = ((result * base) % m))
    (h_trans_base : base' = ((base * base) % m))
    (h_trans_exp : exp' = (exp / 2)) :
    ((exp' ≥ 0)) ∧ ((((result' * (pow base' exp')) % m) = ((pow b e) % m))) ∧ ((result' < m)) := by
  subst_eqs
  obtain ⟨h_exp_pos, h_parity⟩ := h_guard
  obtain ⟨h_e_nn, h_m⟩ := h_pre
  refine ⟨?_, ?_, ?_⟩
  · omega
  · have h_k_nn : exp / 2 ≥ 0 := by omega
    have h_2k_nn : 2 * (exp / 2) ≥ 0 := by omega
    have h_exp_decomp : exp = 2 * (exp / 2) + 1 := by omega
    have h_ax2 : pow base (2 * (exp / 2)) = pow (base * base) (exp / 2) :=
      user_axiom_2 base (exp / 2) h_k_nn
    have h_ax1 : pow base (2 * (exp / 2) + 1) = base * pow base (2 * (exp / 2)) :=
      user_axiom_1 base (2 * (exp / 2)) h_2k_nn
    have h_pow_base_exp : pow base exp = base * pow (base * base) (exp / 2) := by
      conv_lhs => rw [h_exp_decomp]
      rw [h_ax1, h_ax2]
    have h_rewrite_tau : (result * pow base exp) % m =
        ((result * base) * pow (base * base) (exp / 2)) % m := by
      rw [h_pow_base_exp]; ring_nf
    rw [user_axiom_3 ((result * base) % m) (pow ((base * base) % m) (exp / 2)) m h_m]
    rw [Int.emod_emod_of_dvd _ (dvd_refl m)]
    rw [pow_mod_base (base * base) (exp / 2) m h_k_nn h_m]
    rw [← user_axiom_3 (result * base) (pow (base * base) (exp / 2)) m h_m]
    rw [← h_rewrite_tau]
    exact h_tau_1
  · exact Int.emod_lt_of_pos _ (by omega : (0 : Int) < m)

end SynthLean.VerifyTmp
