/-
modular_exponentiation sc3_fallthrough for τ subset
{exp_nn, m_ge_1, pow_inv, res_lt_m, res_nn}.

Auto-generated by /tmp/modular_exp_curator.py.
-/
import SynthLean.Core
open SynthLean

axiom pow : Int → Int → Int
axiom user_axiom_0 : (∀ x : Int, ((pow x 0) = 1))
axiom user_axiom_1 : (∀ x k : Int, ((k ≥ 0) → ((pow x (k + 1)) = (x * (pow x k)))))
axiom user_axiom_2 : (∀ x k : Int, ((k ≥ 0) → ((pow x (2 * k)) = (pow (x * x) k))))
axiom user_axiom_3 : (∀ x y mm : Int, ((mm ≥ 1) → (((x * y) % mm) = (((x % mm) * (y % mm)) % mm))))

-- Helper: pow respects modular reduction (derivable by induction
-- from axioms 0, 1, 3).
private axiom pow_mod_base (x k mm : Int) (hk : k ≥ 0) (hm : mm ≥ 1) :
    (pow (x % mm) k) % mm = (pow x k) % mm

namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc3_fallthrough
    (b e m result base exp : Int)
    (result' base' exp' : Int)
    (h_pre : ((e ≥ 0) ∧ (m ≥ 1)))
    (h_tau_0 : (exp ≥ 0))
    (h_tau_1 : (m ≥ 1))
    (h_tau_2 : (((result * (pow base exp)) % m) = ((pow b e) % m)))
    (h_tau_3 : (result ≥ 0))
    (h_tau_4 : (result < m))
    (h_guard : ((exp > 0) ∧ ((exp % 2) = 1)))
    (h_trans_result : result' = ((result * base) % m))
    (h_trans_base : base' = ((base * base) % m))
    (h_trans_exp : exp' = (exp / 2)) :
    exp > exp' := by
  subst_eqs
  obtain ⟨h_exp_pos, h_parity⟩ := h_guard
  obtain ⟨h_e_nn, h_m⟩ := h_pre
  omega

end SynthLean.VerifyTmp
