-- Lean returned ERROR (exit 1):
-- <tmp>.lean:17:2: error: omega could not prove the goal:
-- a possible counterexample may satisfy the constraints
--   d ≤ -1
--   c ≥ 1
--   a ≥ 0
-- where
--  a := e
--  c := m
--  d := exp

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom pow : Int → Int → Int
axiom user_axiom_0 : (∀ x : Int, ((pow x 0) = 1))
axiom user_axiom_1 : (∀ x k : Int, ((k ≥ 0) → ((pow x (k + 1)) = (x * (pow x k)))))
axiom user_axiom_2 : (∀ x k : Int, ((k ≥ 0) → ((pow x (2 * k)) = (pow (x * x) k))))
axiom user_axiom_3 : (∀ x y mm : Int, ((mm ≥ 1) → (((x * y) % mm) = (((x % mm) * (y % mm)) % mm))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc6_fallthrough
    (b e m result base exp : Int)
    (h_pre : ((e ≥ 0) ∧ (m ≥ 1))) :
    exp ≥ 0 := by
  omega
end SynthLean.VerifyTmp
