-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom is_valid_pm : Int → Int → Int → Int → Int
axiom is_max_matching : Int → Int → Int → Int
axiom empty_matching : Int
axiom step_glover : Int → Int → Int → Int
axiom step_greedy_first : Int → Int → Int → Int
axiom step_bucket_assign : Int → Int → Int → Int
axiom step_skip : Int → Int → Int
axiom user_axiom_0 : (∀ G_ n_ : Int, ((is_valid_pm G_ n_ 0 (empty_matching )) = 1))
axiom user_axiom_1 : (∀ G_ n_ M_ : Int, (((is_valid_pm G_ n_ n_ M_) = 1) → ((is_max_matching G_ n_ M_) = 1)))
axiom user_axiom_2 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (step_glover G_ M_ k_)) = 1)))
axiom user_axiom_3 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (step_greedy_first G_ M_ k_)) = 1)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc0_fallthrough
    (G B n M i : Int)
    (M' i' : Int)
    (h_pre : (n ≥ 0))
    (h_init_i : i' = 0)
    (h_init_M : M' = (empty_matching )) :
    (((is_valid_pm G n i' M') = 1)) ∧ ((0 ≤ i')) ∧ ((i' ≤ n)) := by
  subst_eqs
  refine ⟨?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; first | rfl | omega | nlinarith | (aesop; done)))
end SynthLean.VerifyTmp
