-- Lean returned UNKNOWN: tactic chain didn't close.
-- Lean output tail:
-- <tmp>.lean:27:352: error: tactic 'aesop' failed, made no progress
-- Initial goal:
--   G B n M i M' i' : ℤ
--   h_pre : 0 ≤ n
--   h_tau_0 : 0 ≤ i'
--   h_not_g : n ≤ i'
--   ⊢ is_max_matching G n M' = 1

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom is_valid_pm : Int → Int → Int → Int → Int
axiom is_max_matching : Int → Int → Int → Int
axiom empty_matching : Int
axiom step_glover : Int → Int → Int → Int
axiom step_greedy_first : Int → Int → Int → Int
axiom step_bucket_assign : Int → Int → Int → Int
axiom step_skip : Int → Int → Int
axiom user_axiom_0 : (∀ G_ n_ : Int, ((is_valid_pm G_ n_ 0 (empty_matching )) = 1))
axiom user_axiom_1 : (∀ G_ n_ M_ : Int, (((is_valid_pm G_ n_ n_ M_) = 1) → ((is_max_matching G_ n_ M_) = 1)))
axiom user_axiom_2 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (step_glover G_ M_ k_)) = 1)))
axiom user_axiom_3 : (∀ G_ n_ k_ M_ : Int, (((0 ≤ k_) ∧ (k_ < n_) ∧ ((is_valid_pm G_ n_ k_ M_) = 1)) → ((is_valid_pm G_ n_ (k_ + 1) (step_greedy_first G_ M_ k_)) = 1)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc7_fallthrough
    (G B n M i : Int)
    (M' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (0 ≤ i'))
    (h_not_g : ¬ ((i' < n))) :
    ((is_max_matching G n M') = 1) := by
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2, user_axiom_3]; first | rfl | omega | nlinarith | (aesop; done))
end SynthLean.VerifyTmp
