-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:22:402: warning: This simp argument is unused:
--   user_axiom_1
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵0̵,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵1̵]̵u̲s̲e̲r̲_̲a̲x̲i̲o̲m̲_̲0̲]̲
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom prod : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((prod A 0) = 1)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k : Int, ((k ≥ 0) → ((prod A (k + 1)) = ((prod A k) * (A k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc1_fallthrough
    (n p i : Int)
    (A : Int → Int)
    (p' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (p = (prod A i)))
    (h_guard : (i < n))
    (h_trans_p : p' = (p * (A i)))
    (h_trans_i : i' = (i + 1)) :
    (p' = (prod A i')) := by
  subst_eqs
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop))
end SynthLean.VerifyTmp
