-- Lean returned ERROR (exit 1):
-- <tmp>.lean:17:2: error: omega could not prove the goal:
-- a possible counterexample may satisfy the constraints
--   a ≥ 0
--   a - b ≤ -1
-- where
--  a := n
--  b := i

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom prod : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((prod A 0) = 1)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k : Int, ((k ≥ 0) → ((prod A (k + 1)) = ((prod A k) * (A k)))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc3_fallthrough
    (n p i : Int)
    (A : Int → Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (p = (prod A i))) :
    (n - i) ≥ 0 := by
  omega
end SynthLean.VerifyTmp
