-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:24:455: warning: This simp argument is unused:
--   user_axiom_2
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵2̵]
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((count A 0) = 0)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) = 0)) → ((count A (k + 1)) = ((count A k) + 1))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) ≠ 0)) → ((count A (k + 1)) = (count A k))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc4_fallthrough
    (n c i : Int)
    (A : Int → Int)
    (i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (c = (count A i)))
    (h_tau_1 : (n ≥ 0))
    (h_guard : ((i < n) ∧ ((A i) ≠ 0)))
    (h_trans_i : i' = (i + 1)) :
    ((c = (count A i'))) ∧ ((n ≥ 0)) := by
  subst_eqs
  refine ⟨?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
