-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((count A 0) = 0)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) = 0)) → ((count A (k + 1)) = ((count A k) + 1))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) ≠ 0)) → ((count A (k + 1)) = (count A k))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc5_fallthrough
    (n c i : Int)
    (A : Int → Int)
    (i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (c = (count A i)))
    (h_tau_1 : (n ≥ 0))
    (h_guard : ((i < n) ∧ ((A i) ≠ 0)))
    (h_trans_i : i' = (i + 1)) :
    (n - i) > (n - i') := by
  omega
end SynthLean.VerifyTmp
