-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:21:274: warning: This simp argument is unused:
--   user_axiom_2
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵2̵]
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count : (Int → Int) → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), ((count A 0) = 0)
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) = 0)) → ((count A (k + 1)) = ((count A k) + 1))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k : Int, (((k ≥ 0) ∧ ((A k) ≠ 0)) → ((count A (k + 1)) = (count A k))))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc7_fallthrough
    (n c i : Int)
    (A : Int → Int)
    (c' i' : Int)
    (h_pre : (n ≥ 0))
    (h_tau_0 : (c' = (count A i')))
    (h_tau_1 : (i' ≤ n))
    (h_not_g : ¬ ((i' < n))) :
    (c' = (count A n)) := by
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; first | rfl | omega | nlinarith | (aesop; done))
end SynthLean.VerifyTmp
