-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:20:137: warning: This simp argument is unused:
--   user_axiom_2
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config := { failIfUnchanged := false }) [store,
--   ̲  ̲ ̲ ̲store2d, user_axiom_0, user_axiom_1,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵2̵]
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count_eq : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ v : Int, ((count_eq A 0 v) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A (k + 1) v) = ((count_eq A k v) + (if ((A k) = v) then 1 else 0)))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A k v) ≥ 0)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc1_fallthrough
    (n candidate i cnt : Int)
    (A : Int → Int)
    (h_pre : ((n ≥ 1) ∧ (∃ v : Int, ((count_eq A n v) > (n / 2)))))
    (h_tau_0 : (i ≤ n))
    (h_tau_1 : (∀ v : Int, ((cnt + (count_eq A i candidate)) ≥ (count_eq A i v))))
    (h_g_loop : (i < n)) :
    ((cnt = 0)) ∨ ((cnt > 0)) := by
  first | omega | nlinarith | (decide) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; first | omega | nlinarith | (aesop; done) | decide) | (aesop; done) | (by_contra h; push_neg at h; omega)
end SynthLean.VerifyTmp
