-- Lean returned ERROR (exit 1):
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`
-- <tmp>.lean:27:455: warning: This simp argument is unused:
--   user_axiom_2
-- 
-- Hint: Omit it from the simp argument list.
--   simp_all (config :=
--   ̲  ̲ ̲ ̲{ failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1,̵ ̵u̵s̵e̵r̵_̵a̵x̵i̵o̵m̵_̵2̵]
-- 
-- Note: This linter can be disabled with `set_option linter.unusedSimpArgs false`

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count_eq : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ v : Int, ((count_eq A 0 v) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A (k + 1) v) = ((count_eq A k v) + (if ((A k) = v) then 1 else 0)))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A k v) ≥ 0)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc2_fallthrough
    (n candidate i cnt : Int)
    (A : Int → Int)
    (candidate' i' cnt' : Int)
    (h_pre : ((n ≥ 1) ∧ (∃ v : Int, ((count_eq A n v) > (n / 2)))))
    (h_tau_0 : (i ≤ n))
    (h_tau_1 : (cnt ≥ 0))
    (h_tau_2 : (∀ v : Int, ((cnt + (count_eq A i candidate)) ≥ (count_eq A i v))))
    (h_guard : ((i < n) ∧ (cnt = 0)))
    (h_trans_candidate : candidate' = (A i))
    (h_trans_cnt : cnt' = 1)
    (h_trans_i : i' = (i + 1)) :
    ((i' ≤ n)) ∧ ((cnt' ≥ 0)) ∧ ((∀ v : Int, ((cnt' + (count_eq A i' candidate')) ≥ (count_eq A i' v)))) := by
  subst_eqs
  refine ⟨?_, ?_, ?_⟩
  all_goals (first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2]; first | rfl | omega | nlinarith | (aesop; done)) | (intros; simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0, user_axiom_1, user_axiom_2];    first | omega | nlinarith | (aesop; done)    | (split_ifs <;> first | omega | nlinarith       | (solve_by_elim (config := {maxDepth := 6}))       | aesop)))
end SynthLean.VerifyTmp
