-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count_eq : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ v : Int, ((count_eq A 0 v) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A (k + 1) v) = ((count_eq A k v) + (if ((A k) = v) then 1 else 0)))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A k v) ≥ 0)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc3_fallthrough
    (n candidate i cnt : Int)
    (A : Int → Int)
    (candidate' i' cnt' : Int)
    (h_pre : ((n ≥ 1) ∧ (∃ v : Int, ((count_eq A n v) > (n / 2)))))
    (h_tau_0 : (0 ≤ i))
    (h_tau_1 : (i ≤ n))
    (h_tau_2 : (cnt ≥ 0))
    (h_guard : ((i < n) ∧ (cnt = 0)))
    (h_trans_candidate : candidate' = (A i))
    (h_trans_cnt : cnt' = 1)
    (h_trans_i : i' = (i + 1)) :
    (n - i) > (n - i') := by
  omega
end SynthLean.VerifyTmp
