-- Lean returned ERROR (exit 1):
--   b - c ≥ 1
--   a ≥ 1
--   0 ≤ a - 2*c ≤ 1
--   a - e ≤ -1
-- where
--  a := n
--  b := count_eq A n ⋯.choose
--  c := n / 2
--  d := cnt
--  e := i

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom count_eq : (Int → Int) → Int → Int → Int
axiom user_axiom_0 : ∀ (A : Int → Int), (∀ v : Int, ((count_eq A 0 v) = 0))
axiom user_axiom_1 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A (k + 1) v) = ((count_eq A k v) + (if ((A k) = v) then 1 else 0)))))
axiom user_axiom_2 : ∀ (A : Int → Int), (∀ k v : Int, ((k ≥ 0) → ((count_eq A k v) ≥ 0)))
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
theorem sc6_fallthrough
    (n candidate i cnt : Int)
    (A : Int → Int)
    (h_pre : ((n ≥ 1) ∧ (∃ v : Int, ((count_eq A n v) > (n / 2)))))
    (h_tau_0 : (cnt ≥ 0)) :
    (n - i) ≥ 0 := by
  omega
end SynthLean.VerifyTmp
