-- TIMED OUT after 15.0s

-- Generated by synth.lean_backend.verify — DO NOT keep this file.
import SynthLean.Basic
open SynthLean

axiom user_axiom_0 : (0 = 0)
namespace SynthLean.VerifyTmp

set_option linter.unusedVariables false in
set_option linter.unusedSimpArgs false in
theorem sc4_fallthrough
    (n c i : Int)
    (M : Int → Int)
    (G : Int → Int → Int)
    (c' i' : Int)
    (M' : Int → Int)
    (h_pre : ((n ≥ 0) ∧ (∀ k : Int, (((0 ≤ k) ∧ (k < n)) → ((M k) = (-1)))) ∧ (∀ p q : Int, (((0 ≤ p) ∧ (p < n) ∧ (0 ≤ q) ∧ (q < n)) → (((G p) q) = ((G q) p)))) ∧ (∀ p q : Int, (((0 ≤ p) ∧ (p < n) ∧ (0 ≤ q) ∧ (q < n) ∧ (p ≠ q)) → (((G p) q) ≥ 1)))))
    (h_tau_0 : (0 ≤ i'))
    (h_tau_1 : (i' ≤ n))
    (h_tau_2 : (∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n) ∧ (((G k) (M' k)) ≥ 1)))))
    (h_tau_3 : (c' ≥ i'))
    (h_not_g : ¬ ((i' < (n - 1)))) :
    ((∀ k : Int, (((0 ≤ k) ∧ (k < n) ∧ ((M' k) ≠ (-1))) → ((0 ≤ (M' k)) ∧ ((M' k) < n) ∧ (((G k) (M' k)) ≥ 1)))) ∧ (c' ≥ (n - 1))) := by
  first | assumption | omega | nlinarith | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; done) | (aesop; done) | (simp_all (config := { failIfUnchanged := false }) [store, store2d, user_axiom_0]; first | rfl | omega | nlinarith | (aesop; done))
end SynthLean.VerifyTmp
